### PR TITLE
Nested patchwork: Use eglImage for software buffers

### LINKED ISSUE #1399: Libertine apps (xmir) are distorted when in certain *width*
- Device: Nexus 5, OnePlus One (at least)
- Channel: devel, rc

### Steps to reproduce
1 Install a known working desktop app via libertine.
2. Open the app.

### Expected behavior
The app opens properly with UI and layout correctly displayed.

### Actual behavior
The app opens but the UI is distorted.

### Logfiles and additional information

This is basically a copy of https://github.com/ubports/ubuntu-touch/issues/1115, but for width rather than height. Any app width that does not match up with the GPU's tile width will be distorted beyond recognition.

I've been testing mostly on the OnePlus One, which seems to allocate buffers with widths in increments of 128. This is only a problem with Xmir's software rendering, which manually `memcpy()'s` pixels into the buffer. Right now it appears to do it using the destination buffer's width rather than the source's... Stay tuned.

Broken LXTerminal

### PR DESCRIPTION
**Pull request by UniversalSuperBox**
Some Android platforms return a buffer with a stride longer than their width. This wreaks havoc on the glTexImage2D() call, which expects stride to exactly equal width*bytesPerPixel. This caused software rendering clients to experience display corruption.

To fix this, replace the glTexImage2D() calls with the eglImage usage seen in hardware buffers. This would break mesa platforms, but we do not have any platforms using this version of Mir with Mesa.

Better solutions would involve falling back to the gl texture calls when EGLExtensions can't be created, or otherwise falling back to preserve the possibility of software rendering with nested. However, nested is dead and removed in newer versions of Mir. We're essentially supporting unwanted code as it is and replacing our use of nested on most new platforms, like the PinePhone and Raspberry Pi.

Fixes https://github.com/ubports/ubuntu-touch/issues/1399

### CODE REVIEW

**Comment by UniversalSuperBox** [comment]
Another possible solution is here, but it assumes the target platform supports the GL_UNPACK_ROW_LENGTH_EXT extension to OpenGL ES 2.0 (or ES 3.0). I'm not sure if this assumption is safe for our older devices, and the proposed fix also works (at least on Qualcomm, everything I've tested so far).

https://github.com/MirServer/mir/commit/98d91996ed4585e58ca59208a81006e14d632c02

**Comment by UniversalSuperBox** [comment]
This needs more testing on the FP2. My device reliably hits a kernel bug after twenty seconds to a few minutes of running LXTerminal. Kernel log here: https://paste.ubuntu.com/p/DCBPb8kcdq/

**Comment by UniversalSuperBox** [comment]
New test: the crash occurs without this patch too. It's just slightly more interesting. When the kernel log isn't horribly corrupted, it looks like it's trying to dump its entire address space to dmesg: https://paste.ubuntu.com/p/DwYwmqTJTm/

**Comment by UniversalSuperBox** [comment]
New new test: it doesn't appear to be a regression. The FP2 is just unstable, especially when memory starts flying... like in software rendering. Tried on stable with the same container, crashed in a few minutes. https://paste.ubuntu.com/p/wvn5XSmCCN/

Edit: Here's an even more fun log, it's unclear if the memory failed to refresh while the device was rebooting... or, more interestingly, before. https://paste.ubuntu.com/p/KcqPn3ZvbJ/

Either way, I don't think the FP2 should block this PR.

**Comment by UniversalSuperBox** [comment]
To be clear, this ran on my Nexus 5, OnePlus One, and Nexus 7 (2013 Wi-Fi) for about an hour (screen on, LXterminal up but idle) without issues. I'd appreciate more testing on all these devices, and the FP2, and everything not listed. :)

**Review by peat-psuwit — CHANGES_REQUESTED** [review]
Tested on E4.5 and `mir_demo_client_progressbar`. Seems to work here.

However, we forgot to destroy created `EGLImage` when we're destroyed.

https://github.com/ubports/mir/blob/21a0658a0382d2740e55e44d3cf010149bdfb3ea/src/server/graphics/nested/buffer.cpp#L58-L64

**Comment by UniversalSuperBox** [comment]
I've added the deletion logic to PixelAndTextureAccess. It built locally, now let's watch the CI do it.

**Comment by peat-psuwit** [comment]
Hmm, I tested it on M10 FHD, and this happens:
LXTerminal, tinted magenta

For comparison, this is how it's supposed to look like:
LXTerminal, proper color

**Review by peat-psuwit — APPROVED** [review]
After a bit more testing, it seems like the color issue happens only if `-flatten` is passed into Xmir. Perhaps this is a bug in Xmir's surface flattening. (so Xmir does compositing?)

Anyway, I think this is LGTM.

**Pull request merged**
