### PR TITLE
Fix segfault in unity-system-compositor on bullhead

### PR DESCRIPTION
**Pull request by UniversalSuperBox**
The original fix didn't actually fix it, and also this issue affects all of arm64. Time for some 'try now' commits!

Oh yeah, this is the first time I've touched a C++ project, please go easy on me.

### CODE REVIEW

**Comment by UniversalSuperBox** [comment]
Don't merge this yet... or possibly at all

**Comment by NeoTheThird** [comment]
If SSH with friends fails, you know you're in trouble.

**Comment by tsimonq2** [comment]
Try now?

**Comment by UniversalSuperBox** [comment]
This issue was fixed by https://github.com/ubports/unity-system-compositor/commit/1f86697485aacec787c40f87d0c9fdb9ab489ac8

**Pull request closed without merging**
