### PR TITLE
[nested] Make sure we destroy eglImage before class gets destructed

### PR DESCRIPTION
**Pull request by mariogrip**
The old way caused the unique_pointer's destroy func to get triggerd
after the class destruction, this would cause some of the class members
to be destroyed before eglDestroyImage gets called.

This adds destruction of EGLImage to the class deinit func insted, this
way we are sure the class members are still accessible.

This fixes: https://github.com/ubports/unity8/issues/147

### CODE REVIEW

**Comment by NeoTheThird** [comment]
Installed with ubports-qa, opened top and started resizing a teleports window like crazy: Still seeing the free memory dropping fast. Not sure if your patch helped, but it definitely did not fix the problem completely.

**Comment by mariogrip** [comment]
> Installed with ubports-qa, opened top and started resizing a teleports window like crazy: Still seeing the free memory dropping fast. Not sure if your patch helped, but it definitely did not fix the problem completely.

This is indeed to be expected, what me and @UniversalSuperBox discover is that unity8 makes a "screenshot" and displays this on resize/rotate, but it does not get cleaned up before gc happens. This pr fixes the issue where it didn't destroy eglImage. A way to test this is to open and close apps to see if the memory still goes up. Or trigger gc() and see if it returns to normal memory after resize/rotate, you can do this by locking&unlocking the device

**Comment by Flohack74** [comment]
So actually Michael Zanetti´s guess was right @UniversalSuperBox ;)

**Review by UniversalSuperBox — CHANGES_REQUESTED** [review]
Since this will be merged upstream, we should probably add it as a quilt patch to our distribution for now. This will prevent merge conflicts later.

**Comment by fredldotme** [comment]
Tested on MX4, same experience as @NeoTheThird had, still uses memory and crashes Unity8 at a certain point. Logcat is still showing signs of failing eglDestroyImageKHR calls.

```
D/IMGSRV  ( 3301): gralloc_unregister_buffer:1846: ID=2586 ref=1
D/IMGSRV  ( 2532): gralloc_register_buffer:1747: hnd=0xaf0161d0 ID=2606 fd=161 ref=0
E/libEGL  ( 2532): validate_display:285 error 3008 (EGL_BAD_DISPLAY)
D/IMGSRV  ( 2532): gralloc_unregister_buffer:1846: ID=2586 ref=1
D/IMGSRV  ( 3301): gralloc_register_buffer:1747: hnd=0xb064dba8 ID=2606 fd=44 ref=0
D/IMGSRV  ( 3301): gralloc_unregister_buffer:1846: ID=2605 ref=1
D/IMGSRV  ( 2532): gralloc_unregister_buffer:1846: ID=2605 ref=1
D/IMGSRV  ( 3301): gralloc_unregister_buffer:1846: ID=2595 ref=1
D/IMGSRV  ( 2532): gralloc_unregister_buffer:1846: ID=2595 ref=1
D/IMGSRV  ( 2532): gralloc_register_buffer:1747: hnd=0xaf012990 ID=2607 fd=140 ref=0
E/libEGL  ( 2532): validate_display:285 error 3008 (EGL_BAD_DISPLAY)
D/IMGSRV  ( 3301): gralloc_register_buffer:1747: hnd=0xb0604940 ID=2607 fd=23 ref=0
D/IMGSRV  ( 2532): gralloc_register_buffer:1747: hnd=0xaf013518 ID=2624 fd=155 ref=0
E/libEGL  ( 2532): validate_display:285 error 3008 (EGL_BAD_DISPLAY)
D/IMGSRV  ( 3301): gralloc_register_buffer:1747: hnd=0xb064c530 ID=2624 fd=28 ref=0
D/IMGSRV  ( 2532): gralloc_unregister_buffer:1846: ID=2607 ref=1
D/IMGSRV  ( 3301): gralloc_unregister_buffer:1846: ID=2607 ref=1
D/IMGSRV  ( 3301): gralloc_unregister_buffer:1846: ID=2604 ref=1
D/IMGSRV  ( 2532): gralloc_unregister_buffer:1846: ID=2604 ref=1
D/IMGSRV  ( 2532): gralloc_register_buffer:1747: hnd=0xaf0121e0 ID=2625 fd=96 ref=0
E/libEGL  ( 2532): validate_display:285 error 3008 (EGL_BAD_DISPLAY)
```

**Comment by mariogrip** [comment]
> Tested on MX4, same experience as @NeoTheThird had, still uses memory and crashes Unity8 at a certain point. Logcat is still showing signs of failing eglDestroyImageKHR calls.
> 
> ```
> D/IMGSRV  ( 3301): gralloc_unregister_buffer:1846: ID=2586 ref=1
> D/IMGSRV  ( 2532): gralloc_register_buffer:1747: hnd=0xaf0161d0 ID=2606 fd=161 ref=0
> E/libEGL  ( 2532): validate_display:285 error 3008 (EGL_BAD_DISPLAY)
> D/IMGSRV  ( 2532): gralloc_unregister_buffer:1846: ID=2586 ref=1
> D/IMGSRV  ( 3301): gralloc_register_buffer:1747: hnd=0xb064dba8 ID=2606 fd=44 ref=0
> D/IMGSRV  ( 3301): gralloc_unregister_buffer:1846: ID=2605 ref=1
> D/IMGSRV  ( 2532): gralloc_unregister_buffer:1846: ID=2605 ref=1
> D/IMGSRV  ( 3301): gralloc_unregister_buffer:1846: ID=2595 ref=1
> D/IMGSRV  ( 2532): gralloc_unregister_buffer:1846: ID=2595 ref=1
> D/IMGSRV  ( 2532): gralloc_register_buffer:1747: hnd=0xaf012990 ID=2607 fd=140 ref=0
> E/libEGL  ( 2532): validate_display:285 error 3008 (EGL_BAD_DISPLAY)
> D/IMGSRV  ( 3301): gralloc_register_buffer:1747: hnd=0xb0604940 ID=2607 fd=23 ref=0
> D/IMGSRV  ( 2532): gralloc_register_buffer:1747: hnd=0xaf013518 ID=2624 fd=155 ref=0
> E/libEGL  ( 2532): validate_display:285 error 3008 (EGL_BAD_DISPLAY)
> D/IMGSRV  ( 3301): gralloc_register_buffer:1747: hnd=0xb064c530 ID=2624 fd=28 ref=0
> D/IMGSRV  ( 2532): gralloc_unregister_buffer:1846: ID=2607 ref=1
> D/IMGSRV  ( 3301): gralloc_unregister_buffer:1846: ID=2607 ref=1
> D/IMGSRV  ( 3301): gralloc_unregister_buffer:1846: ID=2604 ref=1
> D/IMGSRV  ( 2532): gralloc_unregister_buffer:1846: ID=2604 ref=1
> D/IMGSRV  ( 2532): gralloc_register_buffer:1747: hnd=0xaf0121e0 ID=2625 fd=96 ref=0
> E/libEGL  ( 2532): validate_display:285 error 3008 (EGL_BAD_DISPLAY)
> ```

This is to be expected, unity8 still have issues. The issue i have seen is that discard (https://github.com/ubports/unity8/blob/xenial_-_edge/qml/Components/ItemSnapshot.qml#L37) does not discard the snapshot images before a gc happens, this can take a while to happen, so if you aggressively trigger this it will fill it's memory. 

This fixes mir not cleaning up after destroying a nested buffer, as you can see in the logs it does indeed destroy them, something that didn't happen before.

Before we got `qeglDrvAPI_eglDestroyImageKHR:4773>: EGL_BAD_PARAMETER` this left the Images stuck in memory without getting cleaned. Something this fixes. A better way to test this is to use qtmir-demo-shell, mir-demo or just start and stop apps without rotation/resize. 

`validate_display:261 error 3008 (EGL_BAD_DISPLAY)` is also printed during creation of the images, and they dont seem to cause any memory issues. 

I have been running u8 for 4 days without crash something i could not do without this, then it would crash every 5 hours.

**Comment by NeoTheThird** [comment]
So... what's the plan?

**Comment by Flohack74** [comment]
i would merge it, any issues come up when we merge it to devel anyway. I would take this risk, and focus on seeing what else is missing.

**Pull request merged**
